version: '3.7'

services:
    nginx:
        image: nginx:1.20-alpine
        ports:
            - 8888:80
        volumes:
            - ./src:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php-fpm

    php-fpm:
        build:
            ./php/php-fpm
        volumes:
            - ./src:/var/www
            - ./php/php-fpm/php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql:Z
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
        depends_on:
            - mysql
volumes:
    mysql_data:
        name: mysql_data